# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.synced_folder "..", "/home/vagrant/OAISIM5G"
  config.vm.box = "ubuntu/bionic64"

  config.vm.define :oaisim5g, autostart: false do |oaisim5g|
    oaisim5g.vm.hostname = "oaisim5g"
    oaisim5g.vm.network "private_network", ip: "192.168.60.154", nic_type: "82540EM"
    oaisim5g.vm.network "private_network", ip: "192.168.129.52", nic_type: "82540EM"

    oaisim5g.vm.provider "virtualbox" do |vb|
      vb.name = "oaisim5g"
      vb.linked_clone = true
      vb.customize ["modifyvm", :id, "--memory", "6144"]
      vb.customize ["modifyvm", :id, "--cpus", "4"]
      vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
    end
    oaisim5g.vm.provision "ansible" do |ansible|
      ansible.host_key_checking = false
      ansible.playbook = "../deploy/deploy.yml"
      ansible.inventory_path = "../deploy/hosts"
      ansible.raw_arguments = ENV.fetch("ANSIBLE_ARGS", "").split(";") +
                              ["--timeout=30"]
      ansible.verbose = 'v'
    end
  end
end
